---
# tasks file for ansible-role-acme_client

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ acme_client_log_dir }}"
    mode: 0755
    owner: "{{ acme_client_user }}"
    group: "{{ acme_client_group }}"
    state: directory
  notify: Restart acme_client

- name: Create db directory
  file:
    path: "{{ acme_client_db_dir }}"
    mode: 0755
    owner: "{{ acme_client_user }}"
    group: "{{ acme_client_group }}"
    state: directory
  notify: Restart acme_client

- name: Create acme_client.conf
  template:
    src: acme_client.conf.j2
    dest: "{{ acme_client_conf_file }}"
    validate: echo %s
  notify: Restart acme_client

- name: Start acme_client
  service:
    name: "{{ acme_client_service }}"
    enabled: true
    state: started
